# Generated by Django 3.2.7 on 2024-02-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.CharField(max_length=300)),
                ('ds_category_1', models.CharField(max_length=300)),
                ('ds_category_2', models.CharField(max_length=300)),
                ('ds_category_3', models.CharField(max_length=300)),
                ('ds_category_4', models.CharField(max_length=300)),
                ('ds_category_5', models.CharField(max_length=300)),
                ('fg_status', models.IntegerField()),
                ('fg_dismissal_on_date', models.IntegerField()),
                ('dt_reference_month', models.DateField()),
            ],
        ),
    ]
