# Generated by Django 3.2.7 on 2024-02-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headcount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headcount',
            old_name='fg_dismissal_on_date',
            new_name='fg_dismissal_on_month',
        ),
    ]
